### ISSUE TITLE
How to get confidence score of all seven emotions?

### ISSUE THREAD

**Issue by akshatbhargava123** [thoughtworksarts/EmoPy#10]
Is there a way to get confidence score of all 7 emotions at once instead of using given subsets? If no, can you please suggest a way to do so.

**Comment by allenzdd** [comment]
I have same problem.

**Comment by RunningLeon** [comment]
Had the same problem.
@thoughtworksarts
Just a quick question, what's the point of validating only on some subset of 7 emotions using several combined models?
Thanks.

**Comment by angelicaperez37** [comment]
We currently don't have a model trained on images of all 7 emotions in the repo, but it would be great if someone worked on this and contributed the trained model! The sets of emotions that are supported can be seen in the FERModel class. 

Any of the scripts that train models (e.g. convolutional_model.py) in the examples folder can be used as templates to preprocess data and train a new model. We don't have a full dataset available in the repo, but there are publicly available datasets for research on the web, such as Microsoft FER and Cohn-Kanade.

@RunningLeon We worked with emotion subsets to explore how different combinations affect accuracy.
