### ISSUE TITLE
extended cohin kanade dataset

### ISSUE THREAD

**Issue by sarmadm** [thoughtworksarts/EmoPy#12]
Hi 

I need to work on complete set on extended cohin kanade dataset images , How can I arrange all

the images ?

**Comment by sarmadm** [comment]
HI please reply

**Comment by angelicaperez37** [comment]
Hello, the full dataset can be requested here - http://www.consortium.ri.cmu.edu/ckagree/

**Comment by sarmadm** [comment]
I have the data , but how to create the labels and folders as in  
`EmoPy/EmoPy/examples/image_data/**sample_image_series_directory**/`   ?
