### ISSUE TITLE
Input and output format

### ISSUE THREAD

**Issue by racinmat** [thoughtworksarts/EmoPy#19]
Hi, I use the library but I'm not sure about some details. In your code, even in examples, you directly feed the image in uint8 range ([0, 255]) to the network. Do you perform some kind of normalization inside your models, or not? I'm not sure if I'm supposed to normalize images or if you trained on not normalized data.
Also, I'm a bit confused about the output. In your code you use `normalized_prediction = [x/sum(prediction) for x in prediction]` for normalizing predictions. But the almost standard is to use softmax instead of this kind of normalization. Is there any reason why you use this kind of normalization instead of softmax?

**Comment by microcosm** [comment]
Hi @racinmat - I'm sorry this question wasn't answered - its been almost a year so I will close this. Can you please re-open if you still have this question and we'll try to get someone to help.
