### ISSUE TITLE
ValueError: Target emotions must be a supported subset. Choose from one of the following emotion subset: 

### ISSUE THREAD

**Issue by sarmadm** [thoughtworksarts/EmoPy#20]
Hi

I Fermodel , in the documentations says : 

POSSIBLE_EMOTIONS = ['anger', 'fear', 'calm', 'sadness', 'happiness', 'surprise', 'disgust']

but when I put those in fermodel example , the following error shows : 

ValueError: Target emotions must be a supported subset. Choose from one of the following emotion subset: 
disgust, fear, anger, happiness, calm, surprise
disgust, happiness, surprise
fear, anger, surprise
fear, anger, calm
happiness, anger, calm

**Comment by sarmadm** [comment]
why there is no : conv_model_0123456.hdf5 ?

**Comment by thekatiemcneil** [comment]
@sarmadm I just ran into this same problem. According to `fermodel.py`, you can only use the following subsets of emotions you can use. You cannot have all seven emotions as a possible subset.

`        supported_emotion_subsets = [
            set(['anger', 'fear', 'surprise', 'calm']),
            set(['happiness', 'disgust', 'surprise']),
            set(['anger', 'fear', 'surprise']),
            set(['anger', 'fear', 'calm']),
            set(['anger', 'happiness', 'calm']),
            set(['anger', 'fear', 'disgust']),
            set(['calm', 'disgust', 'surprise']),
            set(['sadness', 'disgust', 'surprise']),
            set(['anger', 'happiness'])
        ]`

I am curious as to why that is. I'd like to have the model look for all emotions.

**Comment by sarmadm** [comment]
I think there is no model weights for the full set of emotions

**Comment by xuv** [comment]
Hello @sarmadm and @thekatiemcneil 
Thank you for your interest in this project.

The latest push in this repo done by @dianagamedi and @emilysachs has greatly improved the models and can now detect up to 7 emotions with increased accuracy. You might want to give it a try and report back here.

**Comment by xuv** [comment]
The latest commit 4cb4c49ec4a43b52271afb90317d51e377bac5d8 implements the prediction of 7 emotions.

**Comment by ppeharda1** [comment]
Hello @xuv 

I tried your latest updated repo with all seven emotions, and i got this error

Using TensorFlow backend.
Initializing FER model parameters for target emotions: ['calm', 'anger', 'happiness', 'surprise', 'disgust', 'fear', 'sadness']
Traceback (most recent call last):
  File "fermodel_example.py", line 5, in <module>
    model = FERModel(target_emotions, verbose=True)
  File "C:\Users\Predrag\Desktop\zavrsniproject\lib\site-packages\EmoPy\src\fermodel.py", line 41, in __init__
    self._initialize_model()
  File "C:\Users\Predrag\Desktop\zavrsniproject\lib\site-packages\EmoPy\src\fermodel.py", line 45, in _initialize_model
    self.model, self.emotion_map = self._choose_model_from_target_emotions()
  File "C:\Users\Predrag\Desktop\zavrsniproject\lib\site-packages\EmoPy\src\fermodel.py", line 112, in _choose_model_from_target_emotions
    return load_model(resource_filename('EmoPy', model_file)), emotion_map
  File "C:\Users\Predrag\Desktop\zavrsniproject\lib\site-packages\keras\engine\saving.py", line 417, in load_model
    f = h5dict(filepath, 'r')
  File "C:\Users\Predrag\Desktop\zavrsniproject\lib\site-packages\keras\utils\io_utils.py", line 186, in __init__
    self.data = h5py.File(path, mode=mode)
  File "C:\Users\Predrag\Desktop\zavrsniproject\lib\site-packages\h5py\_hl\files.py", line 394, in __init__
    swmr=swmr)
  File "C:\Users\Predrag\Desktop\zavrsniproject\lib\site-packages\h5py\_hl\files.py", line 170, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5f.pyx", line 85, in h5py.h5f.open
OSError: Unable to open file (file signature not found)

Can you please help me with that. I am using your EmoPy for my College Project.

Thank you very much!

**Comment by emilysachs** [comment]
Hi @ppeharda1 
Because of the improvements to the model, the file has grown beyond the 100MB limit on GitHub. We're working on fixing some issues with Git Large File Storage, but for now you may be able to run that particular model by downloading and importing the raw file found here: https://github.com/thoughtworksarts/EmoPy/blob/master/EmoPy/models/conv_model_0123456.h5
