### ISSUE TITLE
Looking for good model + weights 

### ISSUE THREAD

**Issue by hugomeyer78** [thoughtworksarts/EmoPy#21]
I am looking for an already trained NN which would provide the best possible score (3 or 7 outputs).  The ones provided by the EmoPy give poor results given the small size of the model. Would you have any drive location, where more robust models would be stored?

**Comment by xuv** [comment]
Hello @hugomeyer78 and thanks for your interest in this project.

The latest push in this repo by @dianagamedi and @emilysachs has greatly improved the models and can now detect up to 7 emotions with increased accuracy. You might want to give it a try.

**Comment by xuv** [comment]
Latest commit 4cb4c49ec4a43b52271afb90317d51e377bac5d8 provides a much larger model with 7 outputs.
