### ISSUE TITLE
I have a question about how to save my personal training model

### ISSUE THREAD

**Issue by asdnima2007** [thoughtworksarts/EmoPy#22]
# model.export_model('output/time_delay_model.json','output/time_delay_weights.h5',"output/time_delay_emotion_map.json", emotion_map)
 
 what is the emotion_map？ may be u can help me。
Thank you

**Comment by octopousprime** [comment]
I had an issue where an error occured when using the model.export.I just replaced (emotion_map) with {"calm": 0, "anger": 1, "happiness": 2} but I still cant use my exported model.
