### ISSUE TITLE
recent README.md push breaking install

### ISSUE THREAD

**Issue by andytwoods** [thoughtworksarts/EmoPy#24]
Hi,
I notice this file was updated v recently. 
https://github.com/thoughtworksarts/EmoPy/blob/master/README.md

When I try to install requirements (after pulling repo from github), I get the below error. When I bodge setup.py long_description='bla', requirements install.

best,
Andy.

    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\andy_\PycharmProjects\emotionary\EmoPy\setup.py", line 4, in <module>
        long_description = fh.read()
      File "c:\users\andy_\appdata\local\programs\python\python37-32\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 17140: character maps to <undefined>

**Comment by satishdash** [comment]
Hey @andytwoods Could you please check again. I believe it's fixed.

**Comment by microcosm** [comment]
@andytwoods please re-open if you still have this problem - thanks
