### ISSUE TITLE
Model file may be corrupted and cannot be opened

### ISSUE THREAD

**Issue by zhouhao-learning** [thoughtworksarts/EmoPy#32]
Hello, I am very happy to see your code, but when I executed the `python fermodel_example.py` command, I found that you have a problem with the model that predicts 7 emotions. I can't open it. Here is the error displayed:
```
Initializing FER model parameters for target emotions: ['anger', 'fear', 'calm', 'sadness', 'happiness', 'surprise', 'disgust']
Traceback (most recent call last):
  File "/home/zh/sda1/人脸识别/微表情分析/EmoPy/EmoPy/examples/fermodel_example.py", line 7, in <module>
    model = FERModel(target_emotions, verbose=True)
  File "/home/zh/sda1/人脸识别/微表情分析/EmoPy/EmoPy/src/fermodel.py", line 41, in __init__
    self._initialize_model()
  File "/home/zh/sda1/人脸识别/微表情分析/EmoPy/EmoPy/src/fermodel.py", line 45, in _initialize_model
    self.model, self.emotion_map = self._choose_model_from_target_emotions()
  File "/home/zh/sda1/人脸识别/微表情分析/EmoPy/EmoPy/src/fermodel.py", line 112, in _choose_model_from_target_emotions
    return load_model(resource_filename('EmoPy', model_file)), emotion_map
  File "/home/zh/sda3/Anaconda3/envs/deep2.0.0/lib/python3.6/site-packages/keras/engine/saving.py", line 417, in load_model
    f = h5dict(filepath, 'r')
  File "/home/zh/sda3/Anaconda3/envs/deep2.0.0/lib/python3.6/site-packages/keras/utils/io_utils.py", line 186, in __init__
    self.data = h5py.File(path, mode=mode)
  File "/home/zh/sda3/Anaconda3/envs/deep2.0.0/lib/python3.6/site-packages/h5py/_hl/files.py", line 394, in __init__
    swmr=swmr)
  File "/home/zh/sda3/Anaconda3/envs/deep2.0.0/lib/python3.6/site-packages/h5py/_hl/files.py", line 170, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 85, in h5py.h5f.open
OSError: Unable to open file (file signature not found)
```

这是我更改以后的预测代码:
```
from EmoPy.src.fermodel import FERModel
from pkg_resources import resource_filename

# target_emotions = ['calm', 'anger', 'happiness']
# target_emotions = ['anger', 'happiness', 'calm']
target_emotions = ['anger', 'fear', 'calm', 'sadness', 'happiness', 'surprise', 'disgust']
model = FERModel(target_emotions, verbose=True)

print('Predicting on disgust image...')
model.predict(resource_filename('EmoPy.examples','image_data/sample_disgust_image.png'))
```
So can you re-update your model files?

**Comment by zhouhao-learning** [comment]
@xuv 
No, it didn't solve, it's two problems, I can't use a model that predicts seven emotions.

**Comment by davsucks** [comment]
In poking around at this it looks like there's a commit [`4cb4c49ec4a43b52271afb90317d51e377bac5d8`](https://github.com/thoughtworksarts/EmoPy/commit/4cb4c49ec4a43b52271afb90317d51e377bac5d8) which introduced the file in question: `EmoPy/models/conv_model_0123456.h5` as a file managed by [`git-lfs`.](https://git-lfs.github.com/) 

I haven't used this tool before so I'm not sure if I'm doing something wrong (maybe I'm just way off). I installed using `brew install git-lfs` and ran `git lfs install` but wasn't able to get the file downloaded. @emilysachs, I noticed your name on the commit, do you have any context on this? I installed EmoPy using the instructions in the readme, but didn't see anything about git-lfs.

**Comment by RamatovInomjon** [comment]
First of all, thanks for the great job! Can you provide model for 7 (or 6) emotions? as @zhouhao-learning  mentioned, it looks existed model corrupted   
thanks!

**Comment by thiagohersan** [comment]
Hello.

I had same error, but then installed git-lfs ***before*** cloning the EmoPy repository and the large files got downloaded with the clone.

(on a mac):
```
brew install git-lfs
git lfs install
git clone git@github.com:thoughtworksarts/EmoPy.git
```

Doing `ls -l EmoPy/models/conv_model_0123456.h5` shows a 114MB file, and I can run the tests and `python fermodel_example.py`:

<img width="696" alt="cmd" src="https://user-images.githubusercontent.com/850815/62408349-46df2480-b59e-11e9-8004-b367dd0549c7.png">

Hope this helps

**Comment by davsucks** [comment]
@RamatovInomjon @zhouhao-learning 
Turns out I was missing a step :)

Can you try installing [Git LFS](https://git-lfs.github.com/) and then running `git lfs pull` before retrying the example?

**Comment by microcosm** [comment]
Looks like @thiagohersan has found the answer. @zhouhao-learning please open a new issue if there are still problems. Thanks

**Comment by Xasin** [comment]
Jsut ran into the same problem again - adding this to the install instruction documentation would be really nice, to prevent others from having to find this issue as well ^^'

**Comment by anjutiwari** [comment]
How are you installing? Are you using a virtual environment and please provide the full error?

**Comment by Xasin** [comment]
@anjutiwari 
It was the *exact* same error as the one listed in the original Issue (above me). The fix also was exactly the same: Delete the git repo, install git-lfs, re-clone the repository then.
It fixed the problem and let me run the recognition with seven different emotions.

I was using a proper virtual environment, installation via brew etc.

A quick edit to say "git-lfs is required to clone all of this repository, run `sudo apt-get install git-lfs` or similar would solve the issue for others.

**Comment by microcosm** [comment]
Should this information be in the readme file?

**Comment by anjutiwari** [comment]
yes, regenerated the issue. In fermodel_example.py changed.

# target_emotions = ['calm', 'anger', 'happiness']
target_emotions = ['anger', 'fear', 'calm', 'sadness', 'happiness', 'surprise', 'disgust'] and it failed with the same error.

* brew install git-lfs
* git lfs install 
* git lfs pull

It worked for me. Thanks.

**Comment by do-sa** [comment]
i wanto use emopy To train custom emotion subset, anger fear sadness happy neutral before model training, i am having trouble in it can anyone help me on this situation
