### ISSUE TITLE
Import Error: cannot import name 'ConvolutionalNNDropout'

### ISSUE THREAD

**Issue by DanielUSPS** [thoughtworksarts/EmoPy#37]
After installing by reverting to previous versions of tensorflow, keras and scipy, I can run the unit tests and all the other examples.

I get the following error when running convolutional_dropout_model.py
Import Error: cannot import name 'ConvolutionalNNDropout'
Strangely, there is no other info to help me debug.

**Comment by DanielUSPS** [comment]
Even when removing the _init_model and fit functions, the error remains. So, it doesn't seem to be a package or version error.

**Comment by DanielUSPS** [comment]
Found the problem. 'pip install emopy' installs an old version of emopy in the lib\site-packages directory. Replacing neuralnets.py with the latest version fixes the problem.

**Comment by mgayari** [comment]
I am facing the same issue. What did you do to correct it?
