### ISSUE TITLE
For CNN of angry, calm and happy, my angry is always 0%

### ISSUE THREAD

**Issue by DanielUSPS** [thoughtworksarts/EmoPy#38]
I am building the example CNN to distinguish between angry, calm and happy. 

Using a 48x48 image size, FER 2013, copying load_model and save_model from keras.models and predict from FERModel, my angry % is always 0. my calm and happy % vary correctly.

I believe my emotions map for FER 2013 is correct, 0 for angry, 3 for happy and 6 for calm.

I get 3 emotions in the resulting json of angry 0, calm 1, and happy 2, but in the predictions, angry is always 0%. Any ideas?

**Comment by DanielUSPS** [comment]
My predict from the example files also has the same problem.

**Comment by DanielUSPS** [comment]
When I try all 7 emotions, only angry and happy are not 0%

**Comment by cptanalatriste** [comment]
@DanielUSPS Is it possible for you to provide an image to replicate the issue?

**Comment by microcosm** [comment]
@DanielUSPS it looks a while since this issue was logged - I'm going to close - please re-open if you are still having a problem and we'll try to find someone who can help
