### ISSUE TITLE
error tensorflow but i have it

### ISSUE THREAD

**Issue by Antwnina** [thoughtworksarts/EmoPy#40]
python deep_versions.py
theano: 1.0.4
tensorflow: 1.14.0
Using TensorFlow backend.
keras: 2.2.4
Antoninas-MacBook-Pro:~ adpk$ 
in deep_versions.py i have the following 
`# theano
import theano
print('theano: %s' % theano.__version__)
# tensorflow
import tensorflow
print('tensorflow: %s' % tensorflow.__version__)
# keras
import keras
print('keras: %s' % keras.__version__)`

**Comment by Antwnina** [comment]
error: library dfftpack has Fortran sources but no Fortran compiler found
    
    ----------------------------------------
Command "/Users/adpk/venv/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-install-o3cah1kz/scipy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/tmp/pip-record-ofwbwmib/install-record.txt --single-version-externally-managed --compile --install-headers /Users/adpk/venv/include/site/python3.7/scipy" failed with error code 1 in /private/tmp/pip-install-o3cah1kz/scipy/
You are using pip version 19.0.3, however version 19.2.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by Antwnina** [comment]
Using cached https://files.pythonhosted.org/packages/d1/ab/d3bed6b92042622d24decc7aadc8877badf18aeca1571045840ad4956d3f/Werkzeug-0.15.5-py2.py3-none-any.whl
tensorboard 1.14.0 has requirement setuptools>=41.0.0, but you'll have setuptools 40.8.0 which is incompatible.
Installing collected packages: coverage, pyyaml, numpy, six, h5py, scipy, keras-applications, keras-preprocessing, keras, lasagne, more-itertools, zipp, importlib-metadata, pluggy, atomicwrites, attrs, pyparsing, packaging, wcwidth, py, pytest, kiwisolver, python-dateutil, cycler, matplotlib, decorator, networkx, PyWavelets, pillow, imageio, scikit-image, joblib, scikit-learn, Theano, scikit-neuralnetwork, gast, google-pasta, termcolor, wheel, markdown, absl-py, grpcio, protobuf, werkzeug, tensorboard, astor, wrapt, tensorflow-estimator, tensorflow, opencv-python, pydot, graphviz, EmoPy

**Comment by microcosm** [comment]
@Antwnina this issue has been without replies for more than six months, so I am going to close it. I'm sorry you didn't get help - if you are still having a problem here please re-open and we'll see if someone can help
