### ISSUE TITLE
problem with run_all.py -- not running

### ISSUE THREAD

**Issue by Antwnina** [thoughtworksarts/EmoPy#42]
(venv) Antoninas-MacBook-Pro:tests adpk$ python run_all.py 
Traceback (most recent call last):
  File "run_all.py", line 1, in <module>
    from EmoPy.tests.unittests.dataloader_test import DataLoaderTest
ModuleNotFoundError: No module named 'EmoPy'

**Comment by Antwnina** [comment]
(venv) Antoninas-MacBook-Pro:EmoPy adpk$ python -m unittest EmoPy/tests/run_all.py
Using TensorFlow backend.
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/__main__.py", line 18, in <module>
    main(module=None)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/main.py", line 100, in __init__
    self.parseArgs(argv)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/main.py", line 147, in parseArgs
    self.createTests()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/main.py", line 159, in createTests
    self.module)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 220, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 220, in <listcomp>
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "/Users/adpk/EmoPy/EmoPy/tests/run_all.py", line 2, in <module>
    from EmoPy.tests.unittests.data_generator_test import DataGeneratorTest
  File "/Users/adpk/EmoPy/EmoPy/tests/unittests/data_generator_test.py", line 5, in <module>
    from EmoPy.src.data_generator import DataGenerator
  File "/Users/adpk/EmoPy/EmoPy/src/data_generator.py", line 5, in <module>
    K.set_image_dim_ordering('th')
AttributeError: module 'keras.backend' has no attribute 'set_image_dim_ordering'
(venv) Antoninas-MacBook-Pro:EmoPy adpk$

**Comment by Antwnina** [comment]
(venv) Antoninas-MacBook-Pro:examples adpk$ python fermodel_example.py
Traceback (most recent call last):
  File "fermodel_example.py", line 1, in <module>
    from EmoPy.src.fermodel import FERModel
ModuleNotFoundError: No module named 'EmoPy'

**Comment by xiongjun19** [comment]
1. for No module named error:
export PYTHONPATH=${PYTHONPATH}:/path/to/your/folder
2. AttributeError: module 'keras.backend' has no attribute 'set_image_dim_ordering'
   I guess your are using a more new version, and the solution is:
  repalce " K.set_image_dim_ordering('th')"  with "K.set_image_dim_ordering('th')"

**Comment by navyakanu** [comment]
>    I guess your are using a more new version, and the solution is:
>    repalce " K.set_image_dim_ordering('th')"  with "K.set_image_dim_ordering('th')"
 
Latest version of what ( are you referring to keras?) python is 3.6, keras is as below
Keras==2.2.5
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.0
Do you mean remove the space? Not able to run after that as well

**Comment by xiongjun19** [comment]
> > I guess your are using a more new version, and the solution is:
> > repalce " K.set_image_dim_ordering('th')"  with "K.set_image_dim_ordering('th')"
> 
> Latest version of what ( are you referring to keras?) python is 3.6, keras is as below
> Keras==2.2.5
> Keras-Applications==1.0.8
> Keras-Preprocessing==1.1.0
> Do you mean remove the space? Not able to run after that as well

I'm sorry !
    the solution is to use "K.common.set_image_dim_ordering('th')"  instead of " K.set_image_dim_ordering('th')"

**Comment by navyakanu** [comment]
Thanks ! It worked for me ! But I think as we are not freezing the version of keras this might be a issue for most of them

**Comment by Antwnina** [comment]
i changed the the command and still there's problem
![2019-11-09-161811_1920x1200_scrot](https://user-images.githubusercontent.com/11801042/68530017-07e30c80-030d-11ea-9144-14230d5184ef.png)
![2019-11-09-161721_1920x1200_scrot](https://user-images.githubusercontent.com/11801042/68530023-15989200-030d-11ea-9ef3-1da976ae3dd1.png)

**Comment by Antwnina** [comment]
pi@raspberrypi:~ $ python3.6 -m unittest EmoPy/EmoPy/tests/run_all.py
Using TensorFlow backend.
Using TensorFlow backend.
Using TensorFlow backend.
Using TensorFlow backend.
E
======================================================================
ERROR: EmoPy (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: EmoPy
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/unittest/loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
  File "/usr/local/lib/python3.6/site-packages/EmoPy-0.0.5-py3.6.egg/EmoPy/__init__.py", line 1, in <module>
    from .src.fermodel import FERModel
  File "/usr/local/lib/python3.6/site-packages/EmoPy-0.0.5-py3.6.egg/EmoPy/src/fermodel.py", line 1, in <module>
    from keras.models import load_model
  File "/usr/local/lib/python3.6/site-packages/keras/__init__.py", line 3, in <module>
    from . import utils
  File "/usr/local/lib/python3.6/site-packages/keras/utils/__init__.py", line 6, in <module>
    from . import conv_utils
  File "/usr/local/lib/python3.6/site-packages/keras/utils/conv_utils.py", line 9, in <module>
    from .. import backend as K
  File "/usr/local/lib/python3.6/site-packages/keras/backend/__init__.py", line 1, in <module>
    from .load_backend import epsilon
  File "/usr/local/lib/python3.6/site-packages/keras/backend/load_backend.py", line 90, in <module>
    from .tensorflow_backend import *
  File "/usr/local/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 5, in <module>
    import tensorflow as tf
ModuleNotFoundError: No module named 'tensorflow'


----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (errors=1)

**Comment by satishdash** [comment]
@Antwnina  Works now. Please check 
```
$ python -m unittest EmoPy/tests/run_all.py
Using TensorFlow backend.
/Users/satish_dash/.pyenv/versions/3.6.6/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/Users/satish_dash/.pyenv/versions/3.6.6/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/Users/satish_dash/.pyenv/versions/3.6.6/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/Users/satish_dash/.pyenv/versions/3.6.6/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:529: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/Users/satish_dash/.pyenv/versions/3.6.6/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:530: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/Users/satish_dash/.pyenv/versions/3.6.6/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:535: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
...........................
----------------------------------------------------------------------
Ran 27 tests in 0.075s

OK
```

**Comment by Antwnina** [comment]
@satishdash i also tried to go inside the folder to run the command..
```
pi@raspberrypi:~/EmoPy $ cd EmoPy/tests/
pi@raspberrypi:~/EmoPy/EmoPy/tests $ python3.6 -m unittest run_all.py
Using TensorFlow backend.
/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
/usr/local/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.4 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)
/usr/local/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: builtins.type size changed, may indicate binary incompatibility. Expected 432, got 412
  return f(*args, **kwds)
/usr/local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/usr/local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/usr/local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
E
======================================================================
ERROR: run_all (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: run_all
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/unittest/loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
  File "/home/pi/EmoPy/EmoPy/tests/run_all.py", line 1, in <module>
    from EmoPy.tests.unittests.dataloader_test import DataLoaderTest
ModuleNotFoundError: No module named 'EmoPy.tests'


----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
```

**Comment by Aronja** [comment]
Hi @Antwnina 

Are you still having issues with this? 

I have tried running the tests with different versions of keras and tensorflow. There seems to have been breaking changes in between tensorflow 1 and 2 so it is crucial to run it with the correct versions. 

Please make sure to use python3.6.6 and install your dependencies in a virtual env using the requirements.txt 

``` pip install -r requirements.txt ```

Note: I updated the scikit-image version a few days ago, so please pull the newest changes before trying

**Comment by Aronja** [comment]
I'm closing this issue as there haven't been any replies in over a month, please reopen if it occurs again
