### ISSUE TITLE
Is there a return value for the predicted value?

### ISSUE THREAD

**Issue by Chizuchizu** [thoughtworksarts/EmoPy#43]
Hi

When using EmoPy, I noticed that "model.predict ()" had no return value.
I want to use the prediction results, but I can't find a setting that returns the prediction results.

Please let me know if you have any.

I am currently making some improvements to the library to get the expected results.

> /EmoPy/src/fermodel.py   60th line
```
# self._print_prediction(prediction[0]) # past
memo = self._print_prediction(prediction[0]) # add
return memo # add
```
>/EmoPy/src/fermodel.py   111th line
```
return [str(dominant_emotion), normalized_prediction[self.emotion_map[emotion]] * 100]
```

**Comment by cptanalatriste** [comment]
Apparently this commit implements the return values you required:

https://github.com/thoughtworksarts/EmoPy/commit/3523f4adf8496072d4dd41768475013ab2a3cd1d

It was pushed in November 2018. Are you working with the latest version?

**Comment by Chizuchizu** [comment]
Yes, I am. I'd like to down the version.(I'm not sure that it works normally.)
Thank you for sharing for me.

Why did it remove the return values?

I’m curious about the reason.

**Comment by cptanalatriste** [comment]
@Chizuchizu not sure about it, I just joined the project :)

Please let me know if you find the new code suitable, so I can close this issue.

**Comment by microcosm** [comment]
It looks like @Chizuchizu is good here - please re-open if you have a problem @Chizuchizu
