### ISSUE TITLE
requirements.txt     是空的

### ISSUE THREAD

**Issue by rovesoul** [thoughtworksarts/EmoPy#46]
通过pip install -r requirements.txt 这个安装失败,因为requirements这个文件里啥也没有.

**Comment by stayrascal** [comment]
The dependencies of this project are defined in setup.py, which is another way to defined dependencies, which will install dependencies when running `pip install -r requirements.txt`,  Could you please double check it, please provide more information if you still meet this problem.

**Comment by satishdash** [comment]
@rovesoul I believe there's no issue in here after @anjutiwari s change.

**Comment by microcosm** [comment]
Thanks all

@rovesoul please open a new issue if you encounter another problem.
