### ISSUE TITLE
No module named “EmoPy”

### ISSUE THREAD

**Issue by sofiyasofie** [thoughtworksarts/EmoPy#59]
I downloaded the file and installed all requirements including the EmoPy module, however when I attempt to run “fermodel_example.py”, I receive the error when importing that there is no module EmoPy. I verified that it is present with all requirements satisfied with pip install EmoPy. I am running the folder in a virtual environment. Why is EmoPy not being recognized when imported in the code, but it is verified as installed in the virtual environment?

**Comment by Aronja** [comment]
Hi Sofiya, 

I did just try to recreate your error, but failed. 
I sourced my virtualenv, then installed the EmoPy by using `pip install EmoPy` and ran fermodel_example.py. The example ran without errors. 

I also tried installing the EmoPy dependencies with `pip install -r requirements.txt`, which is the other option of getting the dependencies installed and was again successful when running the example. 

I would recommend deleting your virtualenv and setting it up again with `pip install -r requirements.txt`. 

In case this should not work, please paste a screenshot of the error you're receiving and another screenshot of `pip freeze` to show all dependencies that you've installed in your virtualenv. 

 I hope this helps,
Astrid

**Comment by Aronja** [comment]
As there hasn't been a reply in a month, I'm closing this issue.
