### ISSUE TITLE
Post on PyPI?

### ISSUE THREAD

**Issue by ErikBoesen** [thoughtworksarts/EmoPy#6]
It would seem to me that uploading this to PyPI, such that it could be installed through pip, is a better solution for using this code in a versatile manner than hacks like importing `sys` to append `../` to the end of the path. This would make EmoPy much easier to include in other projects as it would not require that users maintain a contrived filesystem structure to use it.

**Comment by microcosm** [comment]
Thanks @ErikBoesen that's a helpful suggestion. I know our core developers can't get to that immediately -- if you or others could send a PR, that could speed things up

**Comment by ErikBoesen** [comment]
I'd love to, but this isn't really the kind of thing I as a third party can set up. Tomorrow I'll see about setting as much groundwork as I can without actually publishing it as a package under my ownership.

**Comment by microcosm** [comment]
@ErikBoesen great to have your input! Can you email me on andy [AT] this domain: https://thoughtworksarts.io please? Maybe we can get this done collaboratively -- thanks

**Comment by microcosm** [comment]
This issue was resolved by [this pull request](5cd6f4df81a1e1e4be8a82e6fe9015001f35b3fc).
