### ISSUE TITLE
pip install EmoPy on Python 3.8

### ISSUE THREAD

**Issue by liyuan1115** [thoughtworksarts/EmoPy#60]
Hi, I was trying the code and got hiccups on " pip install EmoPy", and it shows ERROR: Could not find a version that satisfies the requirement EmoPy (from versions: none)
ERROR: No matching distribution found for EmoPy
not knowing what happens, is it because of the version of the Python ? 
Thanks

**Comment by aharwel1** [comment]
Hello, I received the same error ("ERROR: Could not find a version that satisfies the requirement EmoPy (from versions: none) ERROR: No matching distribution found for EmoPy"). Any help is greatly appreciated.

**Comment by anjutiwari** [comment]
It is working for me, Did you follow the instructions in Readme file?

(venvanju) Anjus-MacBook-Pro:EmoPy anjutiwari$ pip install EmoPy
Collecting EmoPy
  Using cached https://files.pythonhosted.org/packages/53/36/3c33149c382fb549c29a255cdbeca59c15bb1fa39d8a321836acb3a4c056/EmoPy-0.0.5-py3-none-any.whl
Requirement already satisfied: tensorflow>=1.10.1 in ./venvanju/lib/python3.6/site-packages (from EmoPy) (1.13.1)
Requirement already satisfied: keras>=2.2.0 in ./venvanju/lib/python3.6/site-packages (from EmoPy) (2.2.4)
Requirement already satisfied: graphviz in ./venvanju/lib/python3.6/site-packages (from EmoPy) (0.13.2)
Requirement already satisfied: h5py in ./venvanju/lib/python3.6/site-packages (from EmoPy) (2.10.0)
Requirement already satisfied: scikit-image>=0.13.1 in ./venvanju/lib/python3.6/site-packages (from EmoPy) (0.16.2)
Requirement already satisfied: opencv-python in ./venvanju/lib/python3.6/site-packages (from EmoPy) (4.1.2.30)
Requirement already satisfied: lasagne in ./venvanju/lib/python3.6/site-packages (from EmoPy) (0.1)
Requirement already satisfied: scikit-learn>=0.19.1 in ./venvanju/lib/python3.6/site-packages (from EmoPy) (0.22)
Requirement already satisfied: numpy<=1.14.5,>=1.13.3 in ./venvanju/lib/python3.6/site-packages (from EmoPy) (1.14.5)
Requirement already satisfied: scikit-neuralnetwork>=0.7 in ./venvanju/lib/python3.6/site-packages (from EmoPy) (0.7)
Requirement already satisfied: scipy>=0.19.1 in ./venvanju/lib/python3.6/site-packages (from EmoPy) (1.0.0)
Requirement already satisfied: pydot in ./venvanju/lib/python3.6/site-packages (from EmoPy) (1.4.1)
Requirement already satisfied: matplotlib>2.1.0 in ./venvanju/lib/python3.6/site-packages (from EmoPy) (3.1.2)
Requirement already satisfied: pytest in ./venvanju/lib/python3.6/site-packages (from EmoPy) (5.3.1)
Requirement already satisfied: protobuf>=3.6.1 in ./venvanju/lib/python3.6/site-packages (from tensorflow>=1.10.1->EmoPy) (3.11.1)
Requirement already satisfied: six>=1.10.0 in ./venvanju/lib/python3.6/site-packages (from tensorflow>=1.10.1->EmoPy) (1.13.0)
Requirement already satisfied: tensorboard<1.14.0,>=1.13.0 in ./venvanju/lib/python3.6/site-packages (from tensorflow>=1.10.1->EmoPy) (1.13.1)
Requirement already satisfied: wheel>=0.26 in ./venvanju/lib/python3.6/site-packages (from tensorflow>=1.10.1->EmoPy) (0.33.6)
Requirement already satisfied: astor>=0.6.0 in ./venvanju/lib/python3.6/site-packages (from tensorflow>=1.10.1->EmoPy) (0.8.1)
Requirement already satisfied: grpcio>=1.8.6 in ./venvanju/lib/python3.6/site-packages (from tensorflow>=1.10.1->EmoPy) (1.25.0)
Requirement already satisfied: gast>=0.2.0 in ./venvanju/lib/python3.6/site-packages (from tensorflow>=1.10.1->EmoPy) (0.3.2)
Requirement already satisfied: keras-applications>=1.0.6 in ./venvanju/lib/python3.6/site-packages (from tensorflow>=1.10.1->EmoPy) (1.0.8)
Requirement already satisfied: termcolor>=1.1.0 in ./venvanju/lib/python3.6/site-packages (from tensorflow>=1.10.1->EmoPy) (1.1.0)
Requirement already satisfied: absl-py>=0.1.6 in ./venvanju/lib/python3.6/site-packages (from tensorflow>=1.10.1->EmoPy) (0.8.1)
Requirement already satisfied: tensorflow-estimator<1.14.0rc0,>=1.13.0 in ./venvanju/lib/python3.6/site-packages (from tensorflow>=1.10.1->EmoPy) (1.13.0)
Requirement already satisfied: keras-preprocessing>=1.0.5 in ./venvanju/lib/python3.6/site-packages (from tensorflow>=1.10.1->EmoPy) (1.1.0)
Requirement already satisfied: pyyaml in ./venvanju/lib/python3.6/site-packages (from keras>=2.2.0->EmoPy) (5.2)
Requirement already satisfied: networkx>=2.0 in ./venvanju/lib/python3.6/site-packages (from scikit-image>=0.13.1->EmoPy) (2.4)
Requirement already satisfied: pillow>=4.3.0 in ./venvanju/lib/python3.6/site-packages (from scikit-image>=0.13.1->EmoPy) (6.2.1)
Requirement already satisfied: PyWavelets>=0.4.0 in ./venvanju/lib/python3.6/site-packages (from scikit-image>=0.13.1->EmoPy) (1.1.1)
Requirement already satisfied: imageio>=2.3.0 in ./venvanju/lib/python3.6/site-packages (from scikit-image>=0.13.1->EmoPy) (2.6.1)
Requirement already satisfied: joblib>=0.11 in ./venvanju/lib/python3.6/site-packages (from scikit-learn>=0.19.1->EmoPy) (0.14.1)
Requirement already satisfied: Theano>=0.8 in ./venvanju/lib/python3.6/site-packages (from scikit-neuralnetwork>=0.7->EmoPy) (1.0.4)
Requirement already satisfied: pyparsing>=2.1.4 in ./venvanju/lib/python3.6/site-packages (from pydot->EmoPy) (2.4.5)
Requirement already satisfied: python-dateutil>=2.1 in ./venvanju/lib/python3.6/site-packages (from matplotlib>2.1.0->EmoPy) (2.8.1)
Requirement already satisfied: cycler>=0.10 in ./venvanju/lib/python3.6/site-packages (from matplotlib>2.1.0->EmoPy) (0.10.0)
Requirement already satisfied: kiwisolver>=1.0.1 in ./venvanju/lib/python3.6/site-packages (from matplotlib>2.1.0->EmoPy) (1.1.0)
Requirement already satisfied: attrs>=17.4.0 in ./venvanju/lib/python3.6/site-packages (from pytest->EmoPy) (19.3.0)
Requirement already satisfied: pluggy<1.0,>=0.12 in ./venvanju/lib/python3.6/site-packages (from pytest->EmoPy) (0.13.1)
Requirement already satisfied: more-itertools>=4.0.0 in ./venvanju/lib/python3.6/site-packages (from pytest->EmoPy) (8.0.2)
Requirement already satisfied: wcwidth in ./venvanju/lib/python3.6/site-packages (from pytest->EmoPy) (0.1.7)
Requirement already satisfied: importlib-metadata>=0.12; python_version < "3.8" in ./venvanju/lib/python3.6/site-packages (from pytest->EmoPy) (1.3.0)
Requirement already satisfied: packaging in ./venvanju/lib/python3.6/site-packages (from pytest->EmoPy) (19.2)
Requirement already satisfied: py>=1.5.0 in ./venvanju/lib/python3.6/site-packages (from pytest->EmoPy) (1.8.0)
Requirement already satisfied: setuptools in ./venvanju/lib/python3.6/site-packages (from protobuf>=3.6.1->tensorflow>=1.10.1->EmoPy) (40.6.2)
Requirement already satisfied: markdown>=2.6.8 in ./venvanju/lib/python3.6/site-packages (from tensorboard<1.14.0,>=1.13.0->tensorflow>=1.10.1->EmoPy) (3.1.1)
Requirement already satisfied: werkzeug>=0.11.15 in ./venvanju/lib/python3.6/site-packages (from tensorboard<1.14.0,>=1.13.0->tensorflow>=1.10.1->EmoPy) (0.16.0)
Requirement already satisfied: mock>=2.0.0 in ./venvanju/lib/python3.6/site-packages (from tensorflow-estimator<1.14.0rc0,>=1.13.0->tensorflow>=1.10.1->EmoPy) (3.0.5)
Requirement already satisfied: decorator>=4.3.0 in ./venvanju/lib/python3.6/site-packages (from networkx>=2.0->scikit-image>=0.13.1->EmoPy) (4.4.1)
Requirement already satisfied: zipp>=0.5 in ./venvanju/lib/python3.6/site-packages (from importlib-metadata>=0.12; python_version < "3.8"->pytest->EmoPy) (0.6.0)
Installing collected packages: EmoPy
Successfully installed EmoPy-0.0.5

**Comment by microcosm** [comment]
Hi @liyuan1115 @aharwel1 if you are still having problems can you open a new issue with more descriptions about your environment, exact steps you have followed, in which order, screenshots or full stack traces where applicable? Thanks
