### ISSUE TITLE
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

### ISSUE THREAD

**Issue by markovao** [thoughtworksarts/EmoPy#68]
Hello,

I am trying to install EmoPy following the steps from README file,  but when I come to the step
" pip install -r requirements.txt" , I get an error -

(venv) Markovas-Air:EmoPy AsusOlha$ pip install -r requirements.txt
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
(venv) Markovas-Air:EmoPy AsusOlha$ 

I would very appreciate if anyone would help me with this issue

**Comment by xuv** [comment]
@markovao from which folder are you running that command?

Also, have you verified that the file `requirements.txt` is in the folder where you are running the command?

**Comment by markovao** [comment]
Thank you, that worked for me
