### ISSUE TITLE
pip install EmoPy does not work

### ISSUE THREAD

**Issue by markovao** [thoughtworksarts/EmoPy#69]
Hello,

while running pip install EmoPy I am facing the Error:
ERROR: Could not find a version that satisfies the requirement EmoPy (from versions: none)
ERROR: No matching distribution found for EmoPy

Can anyone help me with this?

**Comment by xuv** [comment]
@markovao What is your version of Python?

**Comment by markovao** [comment]
I use Python 3.8.3

**Comment by xuv** [comment]
For now, EmoPy requires Python 3.6 to run. You might be able to run it on more recent versions but you might have to apply some changes in the setup files and possibly elsewhere.

**Comment by markovao** [comment]
I installed Python 3.6.6 as it was described in a readme file, but when I tried to run 
$ python3.6 -m venv venv,
I get the following:
-bash: python3.6: command not found

**Comment by xuv** [comment]
If you have followed the README to install Python3.6, you’ve done so using `pyenv`.
And thus the correct command is:

```pyenv exec python3.6 -m venv venv``` 

as stated in the README

**Comment by markovao** [comment]
$ pyenv exec python3.6 -m venv venv
pyenv: python3.6: command not found

The `python3.6' command exists in these Python versions:
  3.6.6

Note: See 'pyenv help global' for tips on allowing both
      python2 and python3 to be found.


That is what I get

**Comment by Aronja** [comment]
I'm closing this issue as there haven't been any further messages and it seems to be resolved
