### ISSUE TITLE
Version of Python ?

### ISSUE THREAD

**Issue by jccricket** [thoughtworksarts/EmoPy#7]
Hello,
I'm not clear why there is a need for Python version 3.6.3 to run EmoPy ?
What about more recent Python version ? Will it work as well ?
Some platforms do not have Python 3.6.3, and I'm wondering which other one I can use.
Thank you !

**Comment by microcosm** [comment]
Version 3.6.3 was just the version we used. So long as you are using Python 3 there shouldn't be a problem. I have updated the readme to make it clearer you can use any version of Python
