### ISSUE TITLE
Tensorflow version not specified in requirements.txt

### ISSUE THREAD

**Issue by akshatbhargava123** [thoughtworksarts/EmoPy#9]
Tensorflow version not specified in requirements.txt due to which I'm facing problem. After installing from official docs, it shows some error related to version mismatch of tensorflow and keras.

**Comment by angelicaperez37** [comment]
Thanks for pointing this out, we will update requirements.txt. We are currently using tensorflow 1.10.1 and keras 2.2.0. Let us know if you're still facing any issues.
